In [ ]:
import networkx as nx
import pandas as pd
import numpy as np
import matplotlib as plt

In [ ]:
#set parameters
vertices = 1000
adjacencies = 100
pi_vals = [0.25, 0.5, 0.75]
num_trials = 1000

In [ ]:
replicate = {}

In [ ]:
G = nx.random_regular_graph(2, 10)
A = nx.adjacency_matrix(G).todense()
W = np.random.binomial(1, 0.25, 10)
noise = np.random.normal(0, 1, 10)
Y = (W @ A)/200 + W * (1/2) + noise
average_direct_effect = (np.dot(Y,W))/sum(W) - (np.dot(Y, (1-W)))/sum((1-W))
#ADE.append(average_direct_effect)
average_indirect_effect = ((np.dot(Y, A @ W))/sum(A @ W) - (np.dot(Y, A @ (1-W)))/sum(A @ (1-W)))
A_W = np.multiply(A, np.array([W,]*A.shape[0]))
A_1_W = np.multiply(A, np.array([(1-W),]*A.shape[0]))
print(np.dot(Y, A_W))
print(A_W)
print(np.sum(A_W, axis=0))
average_indirect_effect = ((np.dot(Y, A_W))/sum(W) - (np.dot(Y, A_1_W))/sum(1-W))
#AIE.append(average_indirect_effect)
#AIE.append(average_indirect_effect)

[ 0.          0.          0.          0.         -3.31162933  0.
  0.          0.00718819  3.62648258  0.        ]
[[0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[0 0 0 0 2 0 0 2 2 0]


In [ ]:
def average_indirect_effect2(adjacency_matrix, treatment_vector, outcome_vector):
    n = len(outcome_vector)

    # Calculate the effects of changing unit i's treatment on the outcome of all other units
    effects_matrix =  np.outer(treatment_vector, outcome_vector) - np.outer(1 - treatment_vector, outcome_vector)

    # Exclude the effect on the unit being intervened on (diagonal elements)
    np.fill_diagonal(effects_matrix, 0)

    # Calculate the average indirect effect
    avg_indirect_effect = effects_matrix.sum(axis=0) / (n )

    return avg_indirect_effect

result = average_indirect_effect2(A, W, Y)
print("Average Indirect Effect:", np.mean(result))

Average Indirect Effect: -0.6854009197306025


In [ ]:
ADE = []
AIE = [] # poonam said sus abt this?
for i in range(20):
  G = nx.random_regular_graph(adjacencies, vertices)
  #A = nx.adjacency_matrix(G).todense()
  A = np.ones((vertices, vertices)) - np.eye(vertices)
  W = np.random.binomial(1, 0.25, vertices)
  noise = np.random.normal(0, 1, vertices)
  Y = (W @ A)/200 + W * (1/2) + noise
  average_direct_effect = (np.dot(Y,W))/sum(W) - (np.dot(Y, (1-W)))/sum((1-W))
  #ADE.append(average_direct_effect)
  average_indirect_effect = ((np.dot(Y, W @ A))/sum(W) - (np.dot(Y,(1-W) @A))/sum((1-W)))
  #average_direct_effect = (np.dot(Y,W))/sum(W) - (np.dot(Y, (1-W)))/sum((1-W))
  ADE.append(average_direct_effect)
  A_W = np.multiply(A, np.array([W,]*A.shape[0]))
  A_1_W = np.multiply(A, np.array([(1-W),]*A.shape[0]))
  #np.divide(a, b, out=np.zeros_like(a), where=b!=0)
  M = (np.dot(Y, A_W))
  B = np.sum(A_W, axis=0)
  K = np.sum(A_1_W, axis=0)
  P = np.dot(Y, A_1_W)
  result = np.mean(average_indirect_effect2(A, W, Y))
  #average_indirect_effect = np.sum(M)/np.sum(W) - np.sum(P)/np.sum(1-W)
  #average_indirect_effect = np.sum(np.divide(M, B, out=np.zeros_like(B, dtype=float), where=B!=0))/vertices - np.sum(np.divide(P, K, out=np.zeros_like(K, dtype=float), where=K!=0))/vertices
  AIE.append(result)

print(sum(ADE)/len(ADE))
print(sum(AIE)/len(AIE))
#str1 = str(pi)+" ADE"
#str2 = str(pi)+" AIE"
#replicate[str1] = ADE
#replicate[str2] = AIE

0.49792946496796586
-0.6844109628225866


In [ ]:
# AMY's SCRATCH

ADE = []
AIE = [] # poonam said sus abt this?
for i in range(20):
  G = nx.random_regular_graph(adjacencies, vertices)
  #A = nx.adjacency_matrix(G).todense()
  A = np.ones((vertices, vertices)) - np.eye(vertices)
  W = np.random.binomial(1, 0.25, vertices)
  noise = np.random.normal(0, 1, vertices)
  Y = (W @ A)/200 + W * (1/2) + noise
  average_direct_effect = (np.dot(Y,W))/sum(W) - (np.dot(Y, (1-W)))/sum((1-W))
  average_indirect_effect = ((np.dot(Y, W @ A))/sum(W) - (np.dot(Y,(1-W) @A))/sum((1-W)))
  ADE.append(average_direct_effect)
  A_W = np.multiply(A, np.array([W,]*A.shape[0]))
  A_1_W = np.multiply(A, np.array([(1-W),]*A.shape[0]))
  M = (np.dot(Y, A_W))
  B = np.sum(A_W, axis=0)
  K = np.sum(A_1_W, axis=0)
  P = np.dot(Y, A_1_W)
  result = np.mean(average_indirect_effect2(A, W, Y))
  #average_indirect_effect = np.sum(M)/np.sum(W) - np.sum(P)/np.sum(1-W)AIE.append(result)

print(sum(ADE)/len(ADE))
print(sum(AIE)/len(AIE))

In [ ]:
#for pi in pi_vals:
  ADE = []
  AIE = [] # poonam said sus abt this?
  for i in range(1000):
    G = nx.random_regular_graph(adjacencies, vertices)
    A = nx.adjacency_matrix(G).todense()
    W = np.random.binomial(1, pi, vertices)
    noise = np.random.normal(0, 1, vertices)
    Y = (W @ A)/200 + W * (1/2) + noise
    average_direct_effect = (np.dot(Y,W))/sum(W) - (np.dot(Y, (1-W)))/sum((1-W))
#ADE.append(average_direct_effect)
    average_indirect_effect = ((np.dot(Y, A @ W))/sum(A @ W) - (np.dot(Y, A @ (1-W)))/sum(A @ (1-W)))
    #average_direct_effect = (np.dot(Y,W))/sum(W) - (np.dot(Y, (1-W)))/sum((1-W))
    ADE.append(average_direct_effect)

    #average_indirect_effect = ((np.dot(A @ Y, W))/sum(W) - (np.dot(A @ Y, (1-W)))/sum(1-W))/adjacencies
    AIE =

    AIE.append(average_indirect_effect)

  str1 = str(pi)+" ADE"
  str2 = str(pi)+" AIE"
  replicate[str1] = ADE
  replicate[str2] = AIE


In [ ]:
df_r = pd.DataFrame.from_dict(replicate)
df_r.head()

0.25 ADE  0.25 AIE   0.5 ADE   0.5 AIE  0.75 ADE  0.75 AIE
0  0.527691 -0.614731  0.527415  0.403253  0.407795 -1.308796
1  0.572735  0.005011  0.405790  0.604762  0.517513  0.858387
2  0.592484  0.378359  0.476733 -0.073181  0.545724 -0.304052
3  0.450402  0.471055  0.459711  0.562736  0.534248  1.319570
4  0.449293  0.326091  0.557802  0.552592  0.517333  1.711558

In [ ]:
#df_r.to_csv('11_25_23_Simulate_Model_1_1st_0505_Data.csv')

In [ ]:
df_r.mean()

0.25 ADE    0.498266
0.25 AIE    0.389965
0.5 ADE     0.502521
0.5 AIE     0.400440
0.75 ADE    0.501743
0.75 AIE    0.370416
dtype: float64

In [ ]:
df_r.std()

0.25 ADE    0.076446
0.25 AIE    0.007565
0.5 ADE     0.063931
0.5 AIE     0.006480
0.75 ADE    0.072309
0.75 AIE    0.007174
dtype: float64

In [ ]:
results = {'pi': [0.25, 0.5, 0.75], 'ADE': [0.667566, 0.668474, 0.665529],
'AIE': [0.002179, 0.002125, 0.002594]}

In [ ]:
df_r2 = pd.DataFrame.from_dict(results)
df_r2['INF'] = df_r2['ADE'] + df_r2['AIE']


In [ ]:
pd.options.plotting.backend = "plotly"
df_r2.plot(x='pi', y=['ADE', 'AIE', 'INF'])